!!python/object/apply:dotmap.DotMap
dictitems:
  advantage_function: returns-values
  always_full_rollouts: false
  early_termination: null
  first_order: false
  fixed_tasks: false
  inner_lr_init: 0.0
  input_dims: 4
  learn_inner_lr: false
  learn_inner_lr_tensor: false
  learn_offset: false
  log_every: 10
  logdir: /tmp
  max_num_batch_env: 1000
  max_rollout_len: 500
  network_generator: !!python/object:norml.networks.FullyConnectedNetworkGenerator
    activation_fn: !!python/name:tensorflow.python.ops.gen_math_ops.tanh ''
    dim_input: 4
    dim_output: 1
    layer_sizes: !!python/tuple [50, 50]
  num_inner_rollouts: 25
  num_outer_iterations: 1000
  outer_lr_decay: true
  outer_lr_init: 0.0031045541956835963
  outer_optimizer_algo: !!python/name:tensorflow.python.training.adam.AdamOptimizer ''
  output_dims: 1
  pol_log_std_init: -1.0207556372470368
  policy: !!python/name:norml.policies.GaussianPolicy ''
  ppo: true
  ppo_clip_value: 0.2
  random_seed: 44498
  reward_disc: 0.97
  task_env_modifiers:
  - _angle_observation_bias: !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args: [f8, 0, 1]
      state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
    - !!binary |
      h0TnShhXxr8=
  - _angle_observation_bias: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      Po5Fis5Uxr8=
  task_generator: !!python/object/apply:functools.partial
    args: [&id002 !!python/name:norml.envs.cartpole_sensor_bias_env.CartpoleSensorBiasEnv '']
    state: !!python/tuple
    - *id002
    - !!python/tuple []
    - {}
    - null
  tasks_batch_size: 10
  whiten_values: false
state: {_mutable: false}
